theme: jekyll-theme-minimal
logo: logo.PNG
description: "Привет! Меня зовут Анна, я делаю комиксы и иллюстрации."
mywork: "Смотрите мои работы тут:"
instagram: https://www.instagram.com/anna__otter/
behance: https://www.behance.net/otterandpear
google_analytics: UA-163118581-1
